message-backend-ray/messaging/web/src/apps/accounts/urls.py
# -*- coding: utf-8 -*-
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import include, path, reverse

from apps.accounts.views import (
    ChangeEmailView,
    ChangePasswordView,
    ProfileView,
    SettingsView,
)


app_name = "accounts"

urlpatterns = [
    path("profile", login_required(ProfileView.as_view()), name="profile"),
    path(
        "change-password",
        login_required(ChangePasswordView.as_view()),
        name="change-password",
    ),
    path(
        "change-email",
        login_required(ChangeEmailView.as_view()),
        name="change-email",
    ),
    path(
        "settings",
        login_required(SettingsView.as_view()),
        name="settings",
    ),
    path("logout", LogoutView.as_view(next_page="/"), name="logout"),
]

message-backend-ray/messaging/web/src/apps/core/urls.py
from django.contrib.auth import views as auth_view
from django.contrib.auth.decorators import login_required
from django.urls import path, reverse_lazy

from apps.core.views import *


app_name = "core"

view_urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("index_real", IndexRealView.as_view(), name="index-real"),
    path("device_lookup", DeviceLookup.as_view(), name="device-lookup"),
    path("sign-up/", SignUpView.as_view(), name="sign-up"),
    path(
        "personal-info/",
        login_required(PersonalInfoView.as_view()),
        name="personal-info",
    ),
    path(
        "add-device",
        login_required(AddDeviceView.as_view()),
        name="add-device",
    ),
    path(
        "connect",
        login_required(AddDeviceView.as_view()),
        name="add-device",
    ),
    path(
        "pick-plan", login_required(PickPlanView.as_view()), name="pick-plan"
    ),
    path(
        "payment-success",
        login_required(PaymentSuccessView.as_view()),
        name="payment-success",
    ),
    path("login", LoginView.as_view(), name="login"),
    path(
        "replace-device",
        login_required(ReplaceDeviceView.as_view()),
        name="replace-device",
    ),
    path(
        "dashboard", login_required(DashboardView.as_view()), name="dashboard"
    ),
    path(
        "subscription",
        login_required(SubscriptionView.as_view()),
        name="subscription",
    ),
    path("billing", login_required(BillingView.as_view()), name="billing"),
    path(
        "blocked-numbers",
        login_required(BlockedNumbersView.as_view()),
        name="blocked-numbers",
    ),
    path(
        "delete-blocked-number/<int:pk>",
        login_required(DeleteBlockedNumberView.as_view()),
        name="delete-blocked-number",
    ),
    path(
        "success-new-password/",
        auth_view.PasswordResetDoneView.as_view(
            template_name="success_chane_pass.html"
        ),
        name="success-new-password",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_view.PasswordResetConfirmView.as_view(
            template_name="new_password.html",
            success_url=reverse_lazy("core:success-new-password"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "new-password-link/",
        auth_view.PasswordResetDoneView.as_view(
            template_name="password_link.html"
        ),
        name="new-password-link",
    ),
    path(
        "forget-password/",
        auth_view.PasswordResetView.as_view(
            template_name="forget_password.html",
            email_template_name="password_reset_email.txt",
            success_url=reverse_lazy("core:new-password-link"),
        ),
        name="forget-password",
    ),
]

api_urlpatterns = [
    path(
        "create-subscription",
        login_required(CreateSubscriptionAPIView.as_view()),
    ),
    path("update-payment-method", UpdatePaymentMethodAPIView.as_view()),
    path("delete-payment-method", DeletePaymentMethodAPIView.as_view()),
    path("cancel-subscription", CancelSubscriptionAPIView.as_view()),
    path("device-owner", DeviceOwnerApiView.as_view()),
]

urlpatterns = view_urlpatterns + api_urlpatterns

message-backend-ray/messaging/web/src/apps/urls.py
# -*- coding: utf-8 -*-
from django.urls import include, path


urlpatterns = [
    path("accounts/", include("apps.accounts.urls")),
    path("", include("apps.core.urls")),
]

message-backend-ray/messaging/web/src/apps/core/views/add_device.py
from django import views
from django.shortcuts import redirect, render
from django.urls import reverse

from apps.core.consts import OnboardingStepsEnum
from apps.core.forms import DeviceForm
from apps.core.models import Device


class AddDeviceView(views.View):
    template = "onboarding_wizard_form.html"
    form_class = DeviceForm

    def get(self, request):
        form = self.form_class()
        return render(
            request, self.template, {"form": form, **self.base_context}
        )

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            device = Device.objects.get(
                serial_number=form.cleaned_data["serial_number"]
            )
            device.assign_to_user(request.user)
            device.set_nickname(form.cleaned_data["nickname"])
            device.save()
            return redirect(reverse("core:pick-plan"))
        return render(
            request, self.template, {"form": form, **self.base_context}
        )

    @property
    def base_context(self):
        return {
            "title": "Add device",
            "navname": "Please, add your device",
            "action": reverse("core:add-device"),
            "step": OnboardingStepsEnum.ADD_DEVICE.value,
        }

message-backend-ray/messaging/web/src/apps/core/views/billing.py
from django.conf import settings
from django.core.paginator import Paginator
from django.shortcuts import render
from django.views import View

from djstripe.models import Customer
from rest_framework import serializers, status
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from apps.core.consts import ProfileStepsEnum
from apps.utils.djstripe_data import (
    get_card_info_from_payment_method,
    get_plan_info_from_subscription,
)
from apps.utils.stripe import (
    add_customer_payment_method,
    delete_subscription,
    detach_payment_method,
    set_default_payment_method_for_customer,
)


class BillingView(View):
    template = "billing.html"
    page_size = 10

    def get(self, request):
        customer = Customer.objects.get(id=request.user.customer_id)
        invoices = customer.invoices.all().values(
            "status", "created", "invoice_pdf"
        )
        paginator = Paginator(invoices, self.page_size)
        page = paginator.get_page(request.GET.get("page", 1))
        subscription = request.user.customer_subscription
        plan_info = (
            get_plan_info_from_subscription(subscription)
            if subscription
            else None
        )
        card = (
            get_card_info_from_payment_method(customer.default_payment_method)
            if customer.default_payment_method
            else None
        )
        context = {
            "page": page,
            "card": card,
            "plan": plan_info,
        }
        return render(request, self.template, {**self.base_context, **context})

    @property
    def base_context(self):
        return {
            "title": "Billing",
            "navname": "Billing",
            "stripe_api_key": settings.STRIPE_TEST_PUBLIC_KEY,
            "step": ProfileStepsEnum.BILLING.value,
        }


class UpdatePaymentMethodSerializer(serializers.Serializer):
    payment_method_id = serializers.CharField(required=True)


class UpdatePaymentMethodAPIView(APIView):
    serializer_class = UpdatePaymentMethodSerializer
    permission_classes = [IsAuthenticated]

    def post(self, request):
        serializer = self.serializer_class(data=request.data)
        error_message = "Error"
        if serializer.is_valid():
            try:
                data = serializer.validated_data
                user = request.user
                customer = Customer.objects.get(id=user.customer_id)
                if customer.default_payment_method:
                    detach_payment_method(customer.default_payment_method.id)
                add_customer_payment_method(
                    data["payment_method_id"], customer.id
                )
                set_default_payment_method_for_customer(
                    data["payment_method_id"], customer.id
                )
                return Response({"success": True}, status=status.HTTP_200_OK)
            except Exception as e:
                if hasattr(e, "user_message"):
                    error_message = e.user_message
        return Response(
            {"error": error_message}, status=status.HTTP_400_BAD_REQUEST
        )


class DeletePaymentMethodAPIView(APIView):
    permission_classes = [IsAuthenticated]

    def delete(self, request):
        error_message = "Error"
        try:
            user = request.user
            customer = Customer.objects.get(id=user.customer_id)
            detach_payment_method(customer.default_payment_method.id)
            return Response({"success": True}, status=status.HTTP_200_OK)
        except Exception as e:
            if hasattr(e, "user_message"):
                error_message = e.user_message
        return Response(
            {"error": error_message}, status=status.HTTP_400_BAD_REQUEST
        )


class CancelSubscriptionAPIView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        error_message = "Error"
        try:
            user = request.user
            subscription = user.customer_subscription
            delete_subscription(subscription.id)
            return Response({"success": True}, status=status.HTTP_200_OK)
        except Exception as e:
            if hasattr(e, "user_message"):
                error_message = e.user_message
        return Response(
            {"error": error_message}, status=status.HTTP_400_BAD_REQUEST
        )


__all__ = [
    "BillingView",
    "UpdatePaymentMethodAPIView",
    "DeletePaymentMethodAPIView",
    "CancelSubscriptionAPIView",
]

message-backend-ray/messaging/web/src/apps/core/views/blocked_numbers.py
from django.core.paginator import Paginator
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View

from apps.core.consts import ProfileStepsEnum
from apps.core.forms import BlockedNumberForm
from apps.core.models import BlockedNumber


class BlockedNumbersView(View):
    template = "blocked_numbers.html"
    form_class = BlockedNumberForm
    page_size = 10

    def get(self, request, extra_context=None):
        if extra_context is None:
            extra_context = {}
        numbers = BlockedNumber.object.get_user_blocked_numbers(
            request.user
        ).values("id", "number")
        paginator = Paginator(numbers, self.page_size)
        page = paginator.get_page(request.GET.get("page", 1))
        form = self.form_class()
        return render(
            request,
            self.template,
            {**self.base_context, "page": page, "form": form, **extra_context},
        )

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            BlockedNumber.object.add_user_blocked_number(
                form.cleaned_data["number"], request.user
            )
            return self.get(request)
        return self.get(request, {"form": form, "error": True})

    @property
    def base_context(self):
        return {
            "title": "Blocked numbers",
            "navname": "Blocked numbers",
            "step": ProfileStepsEnum.SETTINGS.value,
        }


class DeleteBlockedNumberView(View):
    def post(self, request, pk):
        BlockedNumber.object.delete_user_blocked_number(pk, request.user)
        return redirect(reverse("core:blocked-numbers"))


__all__ = ["DeleteBlockedNumberView", "BlockedNumbersView"]

message-backend-ray/messaging/web/src/apps/core/views/dashboard.py
from django.shortcuts import render
from django.views import View

from apps.core.consts import ProfileStepsEnum
from apps.core.outside_db.services import get_user_message_count


class DashboardView(View):
    template_name = "dashboard.html"

    def get(self, request):
        user = request.user
        # TODO select all in single query
        daily_message_count = get_user_message_count(
            user.twillion_number, "day"
        )
        monthly_message_count = get_user_message_count(
            user.twillion_number, "month"
        )
        yearly_message_count = get_user_message_count(
            user.twillion_number, "year"
        )
        return render(
            request,
            self.template_name,
            {
                **self.base_context,
                "daily": daily_message_count,
                "monthly": monthly_message_count,
                "yearly": yearly_message_count,
            },
        )

    @property
    def base_context(self):
        return {
            "title": "Dashboard",
            "navname": "Dashboard",
            "step": ProfileStepsEnum.DASHBOARD.value,
        }

message-backend-ray/messaging/web/src/apps/core/views/device_lookup.py
from django import views
from django.http import JsonResponse

from apps.core.forms import DeviceLookupForm
from apps.core.models import Device


class DeviceLookup(views.View):
    form_class = DeviceLookupForm

    def get(self, request):
        form = self.form_class(request.GET)
        try:
            if form.is_valid():
                device_id = form.cleaned_data["device_id"]
                user = Device.objects.get(serial_number=device_id).user
                username = user.username
                return JsonResponse(
                    {"status": "true", "email": f"{username}@spacebeaver.com"}
                )
            else:
                message = "Invalid form. Please set device_id"
                return JsonResponse(
                    {"status": "false", "message": message}, status=400
                )

        except:
            message = (
                "Device not configured, please setup and activate account."
            )
            return JsonResponse(
                {"status": "false", "message": message},
                status=402,  # 402 is payment required
            )

message-backend-ray/messaging/web/src/apps/core/views/device_lookup_tests.py
from collections import namedtuple

from django.contrib.auth import get_user_model
from django.test import Client, TestCase

from apps.core.models import Device


User = get_user_model()
UserStub = namedtuple("User", "username full_name email password")
test_user_data = UserStub(
    "farts",
    "test-fullname",
    "somewhere@test.com",
    "&Aqa&5y!8wMpWGUC8gJBWqpxjE8p8nT7XDB2xwZA4$KEb9Nd2&&kv42Y*!Vg4kHE8fPw5k2PwBSD$y*bqzEmXdH8fe#F4#BdY5x",
)
test_device_id = "070065082084083"  # FARTS


class DeviceLookupTestCase(TestCase):
    def setUp(self):
        user = User.objects.create_user(
            username=test_user_data.username,
            full_name=test_user_data.full_name,
            email=test_user_data.email,
        )
        user.is_active = True
        user.set_password(test_user_data.password)
        user.save()
        device = Device(serial_number=test_device_id)
        device.assign_to_user(user)
        device.save()

    def test_lookup_good_device(self):
        c = Client()
        response = c.get("/device_lookup", {"device_id": test_device_id})
        self.assertEqual(response.status_code, 200)

    def test_lookup_bad_device(self):
        c = Client()
        response = c.get("/device_lookup", {"device_id": "farts"})
        self.assertEqual(response.status_code, 402)

    def test_lookup_no_device(self):
        c = Client()
        response = c.get("/device_lookup")
        self.assertEqual(response.status_code, 400)

message-backend-ray/messaging/web/src/apps/core/views/device_owner.py
from rest_framework import serializers, status
from rest_framework.generics import get_object_or_404
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from apps.core.models import Device


class DeviceOwnerRequestSerializer(serializers.Serializer):
    device_id = serializers.CharField()


class DeviceOwnerResponseSerializer(serializers.Serializer):
    twillion_number = serializers.CharField()
    email = serializers.CharField()


class DeviceOwnerApiView(APIView):
    permission_classes = [IsAuthenticated]
    serializer_class = DeviceOwnerRequestSerializer

    def post(self, request):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            serial_number = serializer.validated_data["device_id"]
            device = get_object_or_404(
                Device.objects.all(), serial_number=serial_number
            )
            if not device.user:
                return Response({"message": "Device dont have user"})
            return Response(
                DeviceOwnerResponseSerializer(
                    {
                        "twillion_number": device.user.twillion_number,
                        "email": device.user.email,
                    }
                ).data
            )
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

message-backend-ray/messaging/web/src/apps/core/templates/onboarding_wizard_form.html
{% extends 'registration.html' %}
{% load bootstrap_steps_form %}

{% block content %}   
    {% bootstrap_steps_form form action "Next" "Back" %}


{% endblock %}

message-backend-ray/messaging/web/src/apps/core/templates/password_link.html
{% extends 'spacebeaver.html' %}


{% block content %}
<div class="col-12 col-lg-6 d-flex align-items-center">
    <div class="form-container form-container--centered centered">
      <header class="form-header text-center">
        <img class="form-header-icon" src="{% static 'core/img/svg/icon-aprove.svg' %}" alt="">
        <h1 class="title">Password link has been sent</h1>
        <p class="subtitle">Please check your inbox
        </p>
      </header>
      <footer class="form-footer text-center">
        <a href="{% url 'core:forget-password' %}" class="form-footer-link">Back</a>
      </footer>
    </div>
  </div>
{% endblock %}

message-backend-ray/messaging/web/src/apps/core/templates/registration.html
{% load cms_tags sekizai_tags menu_tags %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'core/style/style.css' %}">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
          integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
          crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
          integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
          crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
          integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
          crossorigin="anonymous"></script>
  <title>SB: {% block title %} {{ title }} {% endblock %}</title>

  {% render_block "css" %}
  {% block extra_head %}  {% endblock %}
</head>
<body>
{% cms_toolbar %}
{% if user.dont_have_active_subscriptions %}
  <div class="alert alert-danger" role="alert">
    You have not active subscription. Click <a href="{% url 'core:subscription' %}">here</a> to solve it.
  </div>
{% endif %}
<!-- NAVBAR -->
<!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'core:index' %}"> SpaceBeaver
      <span class="text-muted">
            {% block navname %} {{ navname }} {% endblock %}
            </span>
    </a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'core:dashboard' %}">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:billing' %}">Billing</a>
        </li>
        {% show_menu 0 100 100 100 "bootstrap_menu.html" %}
      </ul>
    </div>
    <div class="d-flex">
      <div class="btn-group">
        {% if request.user.is_authenticated %}
          <a class="btn btn-primary text-uppercase" href="{% url 'accounts:profile' %}">Profile</a>
          <a class="btn btn-primary text-uppercase" href="{% url 'accounts:logout' %}">Logout</a>
        {% else %}
          <a class="btn btn-primary text-uppercase" href="{% url 'core:login' %}">Login</a>
          <a class="btn btn-success text-uppercase" href="{% url 'core:sign-up' %}">sign up</a>
        {% endif %}

      </div>

    </div>
  </div>
</nav> -->
<!-- END NAVBAR -->
<!-- <div class="page-container"> -->
  <div class="container-fluid p-0 h-100vh">
    <div class="row h-100vh m-0">
        <nav class="side-nav">
            <a  href="{% url 'core:dashboard' %}" class="logo logo-with-beaver">
                <img class="logo__img" src="{% static 'core/img/svg/logo-with-beaver.svg' %}" alt="">
            </a>
          <ul class="progress-bar p-0 side-nav__progress-bar">
            <li class="progress-bar__item ">
                <a href="{% url 'core:personal-info' %}" class="progress-item {% if step == 2 %}progress-item--active{% endif %}">
                    <div class="progress-item__step   {% if step == 2 %}progress-item__step--active{% endif %} {% if step > 2 %}progress-item__step--checked{% endif %}">
                        <span class="progress-item__number {% if step == 2 %}progress-item__number--active{% endif %}">1</span>
                        <span class="progress-item__check {% if step > 2 %}progress-item__check--checked{% endif %}">
                          <img class="progress-item__check-icon" src=" {% static 'core/img/svg/icon-check.svg' %}" alt="">

                        </span>
                    </div>
                    <span class="progress-item__text">Details</span>
                </a>
            </li>
            <li class="progress-bar__item ">
                <a href="{% url 'core:add-device' %}" class="progress-item {% if step == 3 %}progress-item--active{% endif %}">
                    <div class="progress-item__step   {% if step == 3 %}progress-item__step--active{% endif %} {% if step > 3 %}progress-item__step--checked{% endif %}">
                        <span class="progress-item__number {% if step == 3 %}progress-item__number--active{% endif %}">2</span>
                        <span class="progress-item__check {% if step > 3 %}progress-item__check--checked{% endif %}">
                          <img class="progress-item__check-icon" src=" {% static 'core/img/svg/icon-check.svg' %}" alt="">

                        </span>
                    </div>
                    <span class="progress-item__text">Add device</span>
                </a>
            </li>
            <li class="progress-bar__item ">
                <a href="{% url 'core:pick-plan' %}"   class="progress-item {% if step == 4 %}progress-item--active{% endif %}">
                    <div class="progress-item__step   {% if step == 4 %}progress-item__step--active{% endif %} {% if step > 4 %}progress-item__step--checked{% endif %}">
                        <span class="progress-item__number {% if step == 4 %}progress-item__number--active{% endif %}">3</span>
                        <span class="progress-item__check {% if step > 4 %}progress-item__check--checked{% endif %}">
                          <img class="progress-item__check-icon" src=" {% static 'core/img/svg/icon-check.svg' %}" alt="">

                        </span>
                    </div>
                    <span class="progress-item__text">Pick a plan</span>
                </a>
            </li>
            <li class="progress-bar__item ">
                <a  href="{% url 'core:subscription' %}"   class="progress-item {% if step == 5 %}progress-item--active{% endif %}">
                    <div class="progress-item__step   {% if step == 5 %}progress-item__step--active{% endif %} {% if step > 5 %}progress-item__step--checked{% endif %}">
                        <span class="progress-item__number {% if step == 5 %}progress-item__number--active{% endif %}">4</span>
                        <span class="progress-item__check {% if step > 5 %}progress-item__check--checked{% endif %}">
                          <img class="progress-item__check-icon" src=" {% static 'core/img/svg/icon-check.svg' %}" alt="">

                        </span>
                    </div>
                    <span class="progress-item__text">Payment form</span>
                </a>
            </li>
          </ul>
        </nav>
        <main class="main-layout">
          <header class="form-header">
              <h1 class="title">{{ title }}</h1>
              <p class="subtitle">{{ navname }}</p>
          </header>

          {% block content %}

          {% endblock %}
        </main>
  </div>
</div>
{% block footer %}

{% endblock %}
{% render_block "js" %}
{% block extra_js %}  {% endblock %}
</body>
</html>

message-backend-ray/messaging/web/src/apps/core/templates/subscription.html
{% extends 'registration.html' %}

{% block extra_head %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'core/loader.css' %}">
  <script src="https://js.stripe.com/v3/"></script>
  <style>
    .card-container {
      margin: 20px;
    }
  </style>
{% endblock %}

{% block content %}
  <div class="centered col-md-4">
    <form id="payment-form">
      <div class="card-container">

        <div id="card-element">
          <!-- Elements will create input elements here -->
        </div>
      </div>

      <!-- We'll put the error messages in this element -->
      <div id="card-element-errors" role="alert"></div>


      <footer class="form-body__footer d-flex">
        <button type="button" class="btn-outline form-body__footer-btn gap-right">Back</button>
        <button id="submit" type="submit" class="btn form-body__footer-btn" data-toggle="modal" data-target="#successfullyPaid">Next</button>
    </footer>
    </form>
  </div>
  <div id="loader-container">
    <div class="loader-item spinner-border text-primary" role="status">
    </div>
  </div>

  <div class="modal fade" id="successfullyPaid" tabindex="-1" aria-labelledby="successfullyPaidLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content modal__content">
        <div class="modal-body p-0">
            <header class="form-header text-center">
                <img class="form-header-icon" src="{% static 'core/img/svg/icon-aprove.svg' %}" alt="">

                <h1 class="title title--sm">Successfully paid</h1>
                <p class="subtitle">You have successfully paid 200$</p>

            </header>
        </div>
        <div class="modal-footer modal__footer p-0 border-0">
          <button type="button" class="btn modal__footer-btn" data-dismiss="modal" data-toggle="modal" data-target="#successfullyActivated">Activate your account</button>
        </div>
      </div>
    </div>
  </div>


<div class="modal fade" id="successfullyActivated" tabindex="-1" aria-labelledby="successfullyActivatedLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content modal__content">
        <div class="modal-body p-0">
            <header class="form-header text-center">
                <img class="form-header-icon" src="{% static 'core/img/svg/icon-aprove.svg' %}" alt="">
                <h1 class="title title--sm">Successfully activated</h1>
                <p class="subtitle">Your account has been successfully activated and the serial number confirmed</p>

            </header>
        </div>
        <div class="modal-footer modal__footer p-0 border-0">
          <a  href="{% url 'core:dashboard' %}" class="btn modal__footer-btn" >Go to Dashboard</a>
          <!-- data-bs-dismiss="modal" -->
        </div>
      </div>
    </div>
  </div>

{% endblock %}

{% block extra_js %}
  <script>
    let stripe = Stripe("{{ stripe_api_key }}");
    let elements = stripe.elements();
    let card = elements.create('card');


    card.mount('#card-element');
    card.on('change', function (event) {
      displayError(event);
    });


    function setErrorText(text) {
      let displayError = document.getElementById('card-element-errors');
      displayError.textContent = text;
    }

    function displayError(event) {
      if (event.error) {
        setErrorText(event.error.message);
      } else {
        setErrorText("");
      }
    }

    function setLoading(status) {
      const loader = document.getElementById('loader-container');
      loader.style.display = status ? 'block' : 'none'

    }

    function createSubscription({paymentMethodId}) {
      return (
              fetch('/create-subscription', {
                method: 'post',
                headers: {
                  'Content-type': 'application/json',
                  'X-CSRFToken': "{{ csrf_token }}"
                },
                body: JSON.stringify({
                  paymentMethodId: paymentMethodId,
                }),
              })
                      .then(res => res.json())
                      .then(res => {
                        console.log(res);
                        if (res.error) {
                          setErrorText(res.error);
                        } else if (res.object === "subscription" && res.status === "active") {
                          window.location.replace(`${location.origin}{% url "core:payment-success" %}`)
                        } else {
                          setErrorText("Payment error")
                        }
                      })
                      .catch(err => {
                        console.log('catch', err)
                      })
                      .finally(() => setLoading(false))
      );
    }

    function createPaymentMethod({card}) {
      stripe
              .createPaymentMethod({
                type: 'card',
                card: card,
                billing_details: {
                  name: "{{ request.user.full_name }}",
                  email: "{{ request.user.email }}"
                },
              })
              .then((result) => {
                if (result.error) {
                  displayError(result);
                  setLoading(false);
                } else {
                  createSubscription({
                    paymentMethodId: result.paymentMethod.id,
                  });
                }
              });
    }

    const form = document.getElementById('payment-form');

    form.addEventListener('submit', function (ev) {
      ev.preventDefault();
      setLoading(true);
      createPaymentMethod({card});
    });
  </script>
{% endblock %}